apiVersion: v1
kind: ServiceAccount
metadata:
  name: petrov
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ivanov
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grigoriev
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tikhomirov
  namespace: default