apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8srunasnonroot
metadata:
  name: require-runasnonroot
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - "audit-zone"