apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
  namespaces: ["audit-zone"]
  resources:
  - group: ""
    resources: ["pods"]
- level: RequestResponse
  namespaces: ["audit-zone"]
  resources:
  - group: ""
    resources: ["pods"]
  omitStages:
  - RequestReceived
